### ISSUE TITLE
astro-expressive-code not working in mdx files

### ISSUE THREAD

**Issue by NaviTheCoderboi** [expressive-code/expressive-code#211]
hi guys,i am using astro-expressive-code in my astro.js project, i am on astro v4.8

but its not working in .mdx
![image](https://github.com/expressive-code/expressive-code/assets/102732282/05699f5a-141b-4118-8b08-de4e5315ffae)

when i try using `<Code />` component, i get this error
````js
08:34:05 [ERROR] [vite] Internal server error: [postcss] The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received '\x00/_astro/ec.wtfda.css'
  Plugin: vite:css
  File: /_astro/ec.wtfda.css?direct:undefined:NaN
      at Object.statSync (node:fs:1659:10)
      at C:\Users\dell\Desktop\projects\node\portfolio\node_modules\.pnpm\@tailwindcss+postcss@4.0.0-alpha.14_postcss@8.4.38\node_modules\@tailwindcss\postcss\dist\index.js:1:709
      at C:\Users\dell\Desktop\projects\node\portfolio\node_modules\.pnpm\@tailwindcss+postcss@4.0.0-alpha.14_postcss@8.4.38\node_modules\@tailwindcss\postcss\dist\index.js:1:1892
      at _optionalChain (C:\Users\dell\Desktop\projects\node\portfolio\node_modules\.pnpm\@tailwindcss+postcss@4.0.0-alpha.14_postcss@8.4.38\node_modules\@tailwindcss\postcss\dist\index.js:1:687)     
      at S.plugins (C:\Users\dell\Desktop\projects\node\portfolio\node_modules\.pnpm\@tailwindcss+postcss@4.0.0-alpha.14_postcss@8.4.38\node_modules\@tailwindcss\postcss\dist\index.js:1:1821)
      at LazyResult.runOnRoot (C:\Users\dell\Desktop\projects\node\portfolio\node_modules\.pnpm\postcss@8.4.38\node_modules\postcss\lib\lazy-result.js:329:16)
      at LazyResult.runAsync (C:\Users\dell\Desktop\projects\node\portfolio\node_modules\.pnpm\postcss@8.4.38\node_modules\postcss\lib\lazy-result.js:258:26)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async compileCSS (file:///C:/Users/dell/Desktop/projects/node/portfolio/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.11_lightningcss@1.24.1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:32272:25)
      at async TransformContext.transform (file:///C:/Users/dell/Desktop/projects/node/portfolio/node_modules/.pnpm/vite@5.2.11_@types+node@20.12.11_lightningcss@1.24.1/node_modules/vite/dist/node/chunks/dep-cNe07EU9.js:31583:56)
```

my config
```ts
import mdx from "@astrojs/mdx";
import sitemap from "@astrojs/sitemap";
import expressiveCode from "astro-expressive-code";
import { defineConfig } from "astro/config";
import rehypeAutolinkHeadings from "rehype-autolink-headings";
import rehypeSlug from "rehype-slug";

// https://astro.build/config
export default defineConfig({
    prefetch: {
        defaultStrategy: "tap"
    },
    integrations: [
        sitemap(),
        expressiveCode({
            themes: ["one-dark-pro"],
            frames: {
                showCopyToClipboardButton: true
            }
        }),
        mdx({
            optimize: true,
            rehypePlugins: [rehypeSlug, rehypeAutolinkHeadings],
            syntaxHighlight: "shiki",
            shikiConfig: {
                theme: "one-dark-pro"
            }
        })
    ],
    site: "https://navithecoderboi.me"
});
```

**Comment by hippotastic** [comment]
Hello! This is not an Expressive Code issue, but an unfortunate behavior of the MDX integration.

You have added `rehypePlugins: [rehypeSlug, rehypeAutolinkHeadings],` to the options of your `mdx(...)` integration call, which causes the MDX integration to replace all rehype and remark plugins configured in the global Astro markdown config with only the ones you have specified in the MDX options.

This will also disable EC's rehype integration, which `astro-expressive-code` adds to your global Astro markdown config.

To fix your project, move any `rehypePlugins` and `remarkPlugins` out of the MDX integration call, and into Astro's `markdown: { ... }` config options. The MDX integration will also find them there.
