### ISSUE TITLE
build fail: when adding custom theme

### ISSUE THREAD

**Issue by directormac** [expressive-code/expressive-code#218]
I followed [this guide](https://expressive-code.com/guides/themes/#using-themes-from-vs-code)

Build is failing on generating static routes

```sh
 generating static routes
ENOENT: no such file or directory, open '.../dist/chunks/catpuccin.jsonc'
  Stack trace:
    at Object.readFileSync (node:fs:448:20)
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async generatePage (.../mkra.dev/node_modules/.pnpm/astro@4.10.2_@types+node@20.14.2_typescript@5.4.5/node_modules/astro/dist/core/build/generate.js:157:22)
    at async staticBuild (.../node_modules/.pnpm/astro@4.10.2_@types+node@20.14.2_typescript@5.4.5/node_modules/astro/dist/core/build/static-build.js:102:7)
    at async AstroBuilder.run (.../node_modules/.pnpm/astro@4.10.2_@types+node@20.14.2_typescript@5.4.5/node_modules/astro/dist/core/build/index.js:164:7)
 ```
 
 I shortened the path for readability

**Comment by directormac** [comment]
Fixed it needs to be on the root dir.
